name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: johnbeynon/render-deploy-action@v0.0.8
    - name: Deploy to production
      with: |
        service-id: ${{secrets.MY_RENDER_SERVICE_ID}}
        service-id: ${{secrets.MY_RENDER_API_KEY}}
    - name: Render Deploy Action
      # You may pin to the exact commit or the version.
      # uses: johnbeynon/render-deploy-action@a0588f9aca995a15d69a72cb2bfbf37c12e5b540
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        # ID of the service to deploy
        service-id: ${{secrets.MY_RENDER_SERVICE_ID}}
        # A Render API key
        api-key: ${{secrets.MY_RENDER_API_KEY}}
